[workspace]
allow_dirty = false
changelog_update = false
dependencies_update = false
git_release_enable = false
pr_labels = ["release"]
publish_allow_dirty = false
semver_check = true
release_always = false

[[package]]
name = "soar-cli"
git_tag_name = "v{{ version }}"

[[package]]
name = "soar-core"
git_tag_enable = false
