[package]
name = "soar-core"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = { version = "1.5.5", features = ["mmap"] }
chrono = { version = "0.4.39", default-features = false, features = ["now"] }
futures = "0.3.31"
image = { version = "0.25.5", default-features = false, features = ["png"] }
nix = { version = "0.29.0", features = ["ioctl", "term", "user"] }
once_cell = "1.20.2"
rayon = "1.10.0"
regex = { version = "1.11.1", default-features = false, features = ["unicode-case", "unicode-perl", "std"] }
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "blocking", "http2", "json", "stream"] }
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0.215", features = ["derive"] }
soar-db = { version = "0.1.0", path = "../soar-db" }
soar-dl = "0.1.2"
squishy = { version = "0.3.0", features = ["appimage", "rayon"] }
thiserror = "2.0.6"
toml = "0.8.19"
